language: python
dist: trusty
sudo: false

python:
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3.5-5.8.0"

cache: pip

install:
   - ./setup.py develop
   - pip3 install pytest-httpbin
   - pip3 install git+https://github.com/python-trio/trio.git
   - pip3 install git+https://github.com/dabeaz/curio.git
   - pip3 install pylint

script:
  - pytest --verbose --tb=native
  - pylint asks tests

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - "irc.freenode.net#8banana"
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"
